INSERT INTO Instruments VALUES('Recorder', 40, NULL, NULL, 'must bring your own')
INSERT INTO Instruments VALUES('Violin', 50, 210, 40, NULL)
INSERT INTO Instruments VALUES('Viola', 50, 210, 40, NULL)
INSERT INTO Instruments VALUES('Cello', 50, 240, 80, NULL)
INSERT INTO Instruments VALUES('Double bass', 210, 240, 80, NULL)
INSERT INTO Instruments VALUES('Flute', 50, 210, 40, NULL)
INSERT INTO Instruments VALUES('Clarinet', 50, 210, 40, NULL)
INSERT INTO Instruments VALUES('Oboe', 50, 300, 80, NULL)
INSERT INTO Instruments VALUES('Basson', 50, 300, 80, NULL)
INSERT INTO Instruments VALUES('Other woodwind', 300, 40, 80, NULL)
INSERT INTO Instruments VALUES('Trumpet', 50, 210, 40, NULL)
INSERT INTO Instruments VALUES('Trombone', 50, 240, 40, NULL)
INSERT INTO Instruments VALUES('French horn', 50, 240, 80, NULL)
INSERT INTO Instruments VALUES('Tuba', 50, 280, 80, NULL)
INSERT INTO Instruments VALUES('Other bass', 300, 40, 80, NULL)
INSERT INTO Instruments VALUES('Percussion', 50, 280, NULL, NULL)
INSERT INTO Instruments VALUES('Vocal technique', 80, 300, NULL, NULL)
INSERT INTO Instruments VALUES('Music Theory', 80, 300, NULL, NULL)

INSERT INTO Ensembles VALUES(0, 'N/A')
INSERT INTO Ensembles VALUES(1, 'Training')
INSERT INTO Ensembles VALUES(2, 'Training')
INSERT INTO Ensembles VALUES(3, 'Training')
INSERT INTO Ensembles VALUES(4, 'Junior')
INSERT INTO Ensembles VALUES(5, 'Junior')
INSERT INTO Ensembles VALUES(6, 'Junior')
INSERT INTO Ensembles VALUES(7, 'Community')
INSERT INTO Ensembles VALUES(8, 'Community')

INSERT INTO TutorType VALUES('Junior', 15.00)
INSERT INTO TutorType VALUES('Senior', 20.00)
INSERT INTO TutorType VALUES('Head', 40.00)

INSERT INTO Person VALUES('Ray', 'Jackson', '1996-08-28', '0278139659')
INSERT INTO Person VALUES('Luc', 'Tom', '1996-11-30', '0278845565')
INSERT INTO Person VALUES('Ben', 'Gray', '1998-12-11', '065654466')
INSERT INTO Person VALUES('Joe', 'Peat', '1993-02-01', '0986476585')
INSERT INTO Person VALUES('Jack', 'Smith', '1993-01-07', '76674576')
INSERT INTO Person VALUES('Marc', 'Kelly', '1993-04-04', '57575677')

---INSERT INTO Student VALUES((SELECT ID FROM Person WHERE FirstName = 'Ray' AND LastName = 'Jackson' AND DateOfBirth = '1996-08-28' AND PhoneNo = 0278139659), 1)

INSERT INTO Address VALUES('4 Osmond Street', 'South Dunedin', 'Dunedin', 9012)
INSERT INTO Address VALUES('76 Loserville Point', 'Upper Hutt', 'Wellington', 9012)
INSERT INTO Address VALUES('4 Wesily Road', 'St. Clair', 'Dunedin', 9011)

INSERT INTO PersonAddress VALUES(1, 1)
INSERT INTO PersonAddress VALUES(2, 2)
INSERT INTO PersonAddress VALUES(3, 3)
INSERT INTO PersonAddress VALUES(4, 1)
INSERT INTO PersonAddress VALUES(5, 2)
INSERT INTO PersonAddress VALUES(6, 3)

INSERT INTO Student VALUES(1,0)
INSERT INTO Student VALUES(2,1)
INSERT INTO Student VALUES(3,0)

INSERT INTO Parents VALUES(1,4)

INSERT INTO StudentInstrument VALUES(1, 'Tuba', 0)
INSERT INTO StudentInstrument VALUES(1, 'Recorder', 0)
INSERT INTO StudentInstrument VALUES(2, 'Other bass', 1)
INSERT INTO StudentInstrument VALUES(2, 'Oboe', 1)
INSERT INTO StudentInstrument VALUES(3, 'Other bass', 0)
INSERT INTO StudentInstrument VALUES(2, 'Tuba', 0)

INSERT INTO Certifications VALUES(1, 'Tuba', 7, 0)
INSERT INTO Certifications VALUES(2, 'Other bass', 1, 1)
INSERT INTO Certifications VALUES(2, 'Oboe', 6, 0)
INSERT INTO Certifications VALUES(3, 'Other bass', 8, 0)
INSERT INTO Certifications VALUES(2, 'Tuba', 4, 0)
INSERT INTO Certifications VALUES(6, 'Recorder', 8, 0)
INSERT INTO Certifications VALUES(4, 'Tuba', 8, 0)

INSERT INTO Tutors VALUES(6, 'Oboe', 'Head')
INSERT INTO Tutors VALUES(6, 'Recorder', 'Head')
INSERT INTO Tutors VALUES(5, 'Other bass', 'Senior')
INSERT INTO Tutors VALUES(4, 'Tuba', 'Junior')
INSERT INTO Tutors VALUES(6, 'Recorder', 'Junior')

INSERT INTO Venues(Name, Street, Suburb, City, Postcode, Phone) VALUES ('Dunedin Town Hall', '1 Octagon', 'City', 'Dunedin', '9012', '0216546767')
INSERT INTO Venues(Name, Street, Suburb, City, Postcode, Phone) VALUES ('City Centre', '2 South', 'City', 'Dunedin', '9012', '0435445433')

INSERT INTO Performances VALUES(1, '2018-11-22', '16:00', 1)
INSERT INTO Performances VALUES(2, '2018-08-10', '16:00', 0)

INSERT INTO PerformancesStudent VALUES(1,1, 'Recorder')
INSERT INTO PerformancesStudent VALUES(1,2, 'Oboe')

INSERT INTO PerformancesStudent VALUES(2,1, 'Tuba')

INSERT INTO Lessons VALUES(8, 'Recorder', '11:30')
INSERT INTO Lessons VALUES(1, 'Other bass', '10:00')
INSERT INTO Lessons VALUES(2, 'Tuba', '10:30')
INSERT INTO Lessons VALUES(3, 'Tuba', '09:30')
INSERT INTO Lessons VALUES(7, 'Recorder', '11:30')

INSERT INTO LessonTutors VALUES(1, 2)
INSERT INTO LessonTutors VALUES(2, 2)
INSERT INTO LessonTutors VALUES(3, 3)
INSERT INTO LessonTutors VALUES(4, 3)
INSERT INTO LessonTutors VALUES(5, 1)

INSERT INTO LessonStudents VALUES(1,1)
INSERT INTO LessonStudents VALUES(2,2)
INSERT INTO LessonStudents VALUES(1,3)

INSERT INTO SheetMusic VALUES('Hello', 50, 40, 1)
INSERT INTO SheetMusic VALUES('This', 20, 40, 1)
INSERT INTO SheetMusic VALUES('Is', 50, 20, 0)
INSERT INTO SheetMusic VALUES('Sheet', 20, 20, 1)
INSERT INTO SheetMusic VALUES('Music', 40, 0, 0)
INSERT INTO SheetMusic VALUES('Test', 49, 40, 1)
INSERT INTO SheetMusic VALUES('You', 25, 10, 0)

INSERT INTO SheetMusicTutors VALUES(1,1,10,5)

INSERT INTO SheetMusicInstruments VALUES(1,'Recorder')
INSERT INTO SheetMusicInstruments VALUES(1,'Oboe')
